version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: app-pgsql-server
    ports:
      - "5433:5432"
    volumes:
      - app-pgsql-data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    
volumes:
  app-pgsql-data:
    driver: local