// <auto-generated />
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Data.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("integer")
                        .HasColumnName("employee_age");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_name");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("integer")
                        .HasColumnName("employee_type");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employees");

                    b.ToTable("employees", "organization");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeAge = 30,
                            EmployeeName = "Test User",
                            EmployeeType = 0
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeAge = 20,
                            EmployeeName = "Test User2",
                            EmployeeType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
